# Generated by Django 2.1.2 on 2019-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('team', models.CharField(max_length=32)),
                ('is_use', models.IntegerField()),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_admin2_user',
            },
        ),
    ]
