# Generated by Django 2.1.2 on 2019-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20190304_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
