os: linux
sudo: false
dist: trusty
language: php
php:
- '7.1'

cache:
  directories:
  - "${HOME}/.cache/composer/files"
  - "${HOME}/.composer/cache/files"

stages:
- name: test

- name: push
  if: type = push

- name: deploy
  if: type = push

jobs:
  include:

  - stage: test
    services:
      - mysql
    before_script:
      - composer install --prefer-dist
    script:
      - bin/setup.sh
      - bin/test.sh

  - stage: push
    if: branch = master
    services:
      - docker
    script:
      - bin/docker_push.sh

#  - stage: deploy
#    name: deploy-dev
#    if: branch = master
#    env:
#      - CI_TRIGGER_ENV=dev CI_TRIGGER_TARGET=cms-admin-restart
#    script:
#      - bin/deploy.sh

  - stage: deploy
    name: deploy-prod
    if: branch = master AND tag =~ ^\d+\.\d+(\.\d+)?$ # ex) tag = 1.0.0
    env:
      - CI_TRIGGER_ENV=prod CI_TRIGGER_TARGET=cms-admin-restart
    script:
      - bin/deploy.sh

