version: '2'

services:
  web:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    volumes:
      - /tmp/cms-admin:/tmp
    ports:
      - ${DOCKER_PUBLISH_PORT}:80
    cpu_shares: 100
    mem_limit: 209715200 # 200MB
    mem_reservation: 104857600 # 100MB
    environment:
      DEBUG: 0
      SENTRY_KEY: ${SENTRY_KEY}
      SESSION_DOMAIN: ${SESSION_DOMAIN}
      CMS_RPC_URL: ${CMS_RPC_URL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      COUCHBASE_HOST: ${COUCHBASE_HOST}