# Generated by Django 2.1.2 on 2019-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAdmin2Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=50)),
                ('menu_url', models.CharField(max_length=200)),
                ('menu_deep', models.IntegerField()),
                ('menu_order', models.IntegerField()),
                ('is_use', models.IntegerField()),
                ('is_show', models.IntegerField()),
                ('reg_date', models.DateTimeField()),
                ('is_newtab', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_admin2_menu',
            },
        ),
    ]
